### ISSUE TITLE
Deletion not working properly

### ISSUE THREAD

**Issue by ihorbond** [safrazik/vue-file-agent#108]
**Describe the bug**
Hi I'm running your advanced usage example. In single file mode after I selected the file and click x to remove the file count goes back to zero as expected but the file remains shown in the list. If I click remove again I get confirmation window and upon confirmation the file is finally removed. Is this the way onBeforeDelete method was supposed to be written: 

```javascript
      onBeforeDelete: function (fileRecord) {
        var i = this.fileRecordsForUpload.indexOf(fileRecord);
        if (i !== -1) {
            this.fileRecordsForUpload.splice(i, 1);
            this.$refs.vueFileAgent.deleteFileRecord(fileRecord); // will trigger 'delete' event
        } else {
          if (confirm('Are you sure you want to delete?')) {
            this.$refs.vueFileAgent.deleteFileRecord(fileRecord); // will trigger 'delete' event
          }
        }
      },
```

Vue v2 running in latest Google Chrome

**Comment by safrazik** [comment]
As shown in [Advanced Usage](https://safrazik.com/vue-file-agent/#advanced-usage) example,
`fileRecords` array contains ALL the files selected (and preloaded, if any)
`fileRecordsForUpload` contains ONLY the files selected and queued for upload

Since the queued files are not uploaded yet, you don't have to call `deleteFileRecord` method because you may not need `delete` event to be triggered for non uploaded files.

But there is a problem with the example.
The correct version should be:

```javascript
      onBeforeDelete: function (fileRecord) {
        var i = this.fileRecordsForUpload.indexOf(fileRecord);
        if (i !== -1) {
            // this is a to-be-uploaded (non uploaded) file
            this.fileRecordsForUpload.splice(i, 1);
            var k = this.fileRecords.indexOf(fileRecord);
            if (k !== -1) this.fileRecords.splice(k, 1);
            return;
        }
        if (confirm('Are you sure you want to delete?')) {
          this.$refs.vueFileAgent.deleteFileRecord(fileRecord); // will trigger 'delete' event
        }
      },
```

But if you have other ways to identify non uploaded files in your `delete` event handler, your implementation should be fine.
Thanks for bringing this up.
See also #69

**Comment by safrazik** [comment]
This issue can be closed as soon as the documentation demo is updated

**Comment by ihorbond** [comment]
> This issue can be closed as soon as the documentation demo is updated

Thanks for a quick reply. What I ended up with is 

```
    deleteFile (file) {
      this.$refs.vueFileAgent.deleteUpload(this.uploadUrl, this.headers, file)
      this.$refs.vueFileAgent.deleteFileRecord(file) // triggers delete event
    },
    onBeforeDelete (file) {
      const isUploaded = !this.fileRecordsToUpload.includes(file)
      if (isUploaded) {
        // file has been uploaded, delete from server
        confirm('Are you sure you want to delete?') && this.deleteFile(file)
      } else {
        // file hasn't been uploaded yet, delete locally
        this.fileRecordsToUpload = this.fileRecordsToUpload.filter(x => x !== file)
        this.fileRecords = this.fileRecords.filter(x => x !== file)
      }
    }
```
Since I don't need to run any logic after the file has been deleted from server by calling $refs.vueFileAgent.deleteUpload() I don't really need to call $refs.vueFileAgent.deleteFileRecord() right ? IMO rather than maintaining two arrays it would be better to have fileRecord indicate its status e.g selected, queued, uploaded etc. What do you think ? And thanks for all your work on this library, I really like it !

**Comment by safrazik** [comment]
> rather than maintaining two arrays it would be better to have fileRecord indicate its status e.g selected, queued, uploaded etc.

Sounds great. I will keep the `status` idea in mind for `v2`. Since I do kind of an encapsulation with [FileRecord](https://github.com/safrazik/vue-file-agent/blob/master/src/lib/file-record.ts) instances in v1, introduction of new properties (and making them reactive) comes with a cost, which is not the case in v2.

**Comment by safrazik** [comment]
In fact `fileRecordsForUpload` is used only in advanced demo since I had to do certain operations with the queue (for demo). User is free to use their own state management implementations. But `status` property idea could be useful in many scenarios.
