### ISSUE TITLE
Set thumbnail url different than download url?

### ISSUE THREAD

**Issue by green-pigeon** [safrazik/vue-file-agent#125]
Hi. This module is awesome. I started using it recently as attachment viewer.

When I set the initial file list if the files are big, the component is loading a bit slow. That's why I want to set smaller thumbnails for file preview but when the file is clicked I want to open the link to the original file.

Is there a way to set image thumbnail url different than the url that is opened when the file is clicked?
Or can I detect the file click event so I can redirect to different url?

Thanks,
Anna

**Comment by safrazik** [comment]
Custom thumbnail is not supported yet. I'm looking into supporting it in the future.
BTW, For Image and Video thumbnails, a resized image is shown instead of the actual image, but yeah, it will take a little time for larger files to be loaded for resized thumbnail generation.

See these related issues about custom thumbnails:
 #106  #66

**Comment by safrazik** [comment]
Duplicate #66
