### ISSUE TITLE
$attrs is readonly, $listeners is readonly

### ISSUE THREAD

**Issue by Pulstarter** [safrazik/vue-file-agent#33]
Hi! 

I am using the component inside another one and I am getting this error on the console.

I have this versions:

"vue-file-agent": "^1.5.2",
"vue": "2.6.10",
"vue-template-compiler": "2.6.10"

Do you know what it could be?

Best regards

**Comment by safrazik** [comment]
I faced the same issue few days ago when trying to use inside `ValidationObserver` component of `vee-validate`.

It appears to be a common issue among components using TypeScript. The issue with these kind of errors is usually because `Vue` is imported more than once. [Similar Issue](https://github.com/bootstrap-vue/bootstrap-vue/issues/3040)

Maybe this issue with `vue-file-agent` is because of a side effect from TypeScript code refactor since `v1.5`. Please use the following workaround until there is a viable solution. 

The workaround:

For vue-cli (webpack config)

```javascript
  configureWebpack: {
    resolve: {
      alias: {
        vue$: path.resolve(__dirname, 'node_modules/vue/dist/vue.runtime.esm.js'),
      },
    },
  },
```

**Comment by Pulstarter** [comment]
Hi!

Thanks for the response. With that workaround I get another vue error, so I change it to:

```
{
    resolve: {
        alias: {
            'vue': path.resolve('./node_modules/vue')
        }
    },
}
```

and the errors disappears.

Thanks and best regards!
