### ISSUE TITLE
How to add additional data in the POST upload request?

### ISSUE THREAD

**Issue by vinayk7** [safrazik/vue-file-agent#40]
I am using this to upload a gallery images of a user so I need to send the _user_id_ alongwith the files selected

I am using the manual mode, is it possible to pass _user_id_ while using deafult uploader?

`uploadFiles: function() {`
      `    // Using the default uploader. You may use another uploader instead.`
      `    this.$refs.vueFileAgent.upload(this.uploadUrl, this.uploadHeaders, this.filesDataForUpload);`
      `    this.filesDataForUpload = [];`
    `}`

**Comment by safrazik** [comment]
I think maybe you found the answer already (hence the issue was closed immediately). If anyone else is looking for the solution: you can build a custom [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) for POST request. See the upload method in [Docs](https://safrazik.com/vue-file-agent/docs/#methods)

```javascript
// Upload with custom FormData
this.$refs.vueFileAgent.upload(url, headers, filesData, function createFormData(fileData){
  var formData = new FormData();
  formData.append('your-custom-data', 'ABC');
  formData.append('my-file', fileData.file); // this is important! - the actual file for upload
  return formData;
});
```
