### ISSUE TITLE
When a file is larger than the max size, it still lets you upload it.

### ISSUE THREAD

**Issue by MizziM96** [safrazik/vue-file-agent#45]
Hi, 

I noticed that when a file is larger than the max size, the error appears as intended but if you click on it the file the error disappears, and one can do anything with it as usual even uploading the file. I am not sure if this is by design or not. Is there already a way to remove the file or not let it upload after removing the error? 

With the current way, a secondary validation from the back end is needed to recheck the file size. It is always good practice to recheck the data coming from the client-side from the back-end, but this seems to be counter-intuitive to upload the file if it has not even passed the client-side validation. Also, in my opinion, it's not user friendly to just remove the error when clicking on it. Instead of removing the error, I would suggest removing the whole file from the list of files or maybe expose a new event to let the developer do something with it (if there isn't an event already for this and I was not aware of it).

Is there a way to maybe improve upon this or perhaps there is already a way to do this and I could not find it?

Regards

P.S. I left a gif showing the error disappearing and uploading. I replicated this from the code pen demo.

![max-size-error-file-agent](https://user-images.githubusercontent.com/17720973/77916853-0903de80-729a-11ea-9230-c6e543f181a5.gif)

**Comment by safrazik** [comment]
Thanks for reporting the issue.

This was not intended. I agree with your points. Looks like a big issue, and I wonder how it managed to be there without being reported/fixed yet.

Since [version 1.3.5](https://github.com/safrazik/vue-file-agent/releases/tag/1.3.5), a feature was added to dismiss error messages by clicking on them. This had caused the issue you reported.

The immediate workaround is to revert that feature (I don’t know how useful that feature is)

Pull requests are welcome!
