### ISSUE TITLE
Replace base64 encoded image with upload response url 

### ISSUE THREAD

**Issue by Gigiart** [safrazik/vue-file-agent#54]
Because sometimes the mobile snapshot pictures are rotated and it showed upside down, I had to process the image in my back end considering is a lot of work to fix this in front end. So I've try to replace the url key with my  thumbnail url that I get it from my back end but nothing change it as preview, the base64 encoded image is still there. So how can I display my thumbnail, after upload.
Thanks again and thanks for your valuable time - I've noticed that you reply very fast, which is great for all of us that we are using your work

**Comment by safrazik** [comment]
You can use `fileRecord.src()` - See #53

But...

In version [1.3.4](https://github.com/safrazik/vue-file-agent/releases/tag/1.3.4) wrong orientation thumbnail issue was fixed. It was achieved with some basic exif operation (See d25257f61188ac8ecdd9fca4cb49fadb904baf77)

So are you seeing wrong orientation in previews (what you mean by thumbnails)? Can you please post a screenshot so I can have an understanding. Maybe the implementation need to be improved  because, for performance reasons, I only read the first 64 kb to look for exif data.

>  Exif should appear in the first 64 KB, however this is not guaranteed—it may be possible for the Exif to extend beyond - https://stackoverflow.com/questions/3248946/what-is-the-maximum-size-of-jpeg-metadata 

Having said that, you should of course do exif operations on the backend without relying on client side. The client side implementation is provided for better UX only.

---

Thank you for understanding and admiring the value of my time committed. I appreciate it.

**Comment by SkiperX** [comment]
I get a CORS error while loading base 64 because the files are being saved on a different domain. Need the ability to disable base 64.

**Comment by safrazik** [comment]
@SkiperX please create a new issue mentioning the error and browser information. I am not sure what’s happening there. Maybe the CORS issue occurs because of the image resize feature (thumbnail) creation. The resize feature has been implemented because on mobile devices there’s a good chance for memory issues when selecting multiple images. Disabling the resizing feature can be implemented with a prop. But looking at your context, I think it should be ok to disable the resize feature altogether for preloaded images (from a url). I hope I make sense.
