### ISSUE TITLE
Confirmation on delete

### ISSUE THREAD

**Issue by Gigiart** [safrazik/vue-file-agent#59]
How to intercept "before delete" event? I'd like to add a confirmation popup to ask for user confirmation. I have managed to add it over delete custom function but still, deletion is triggered before user click to confirm.Thanks in advance

`async fileDeleted(fileRecord) {
            console.log(this.$refs, fileRecord);
            
            if (await this.$refs.confirmDelete.open('Are you sure?', 'Your picture will be deleted!', { color: 'white' })){
                var i = this.fileRecordsForUpload.indexOf(fileRecord);
                if (i !== -1) {
                    this.fileRecordsForUpload.splice(i, 1);
                } else {
                    this.deleteUploadedFile(fileRecord);
                }
            }
        },`

**Comment by safrazik** [comment]
This feature is missing. Will be implemented in next release (1.7.1)

**Comment by Gigiart** [comment]
I think these is going to be very useful for those of us who need to manipulate data.
beforeUpload( return fileRecords)
afterUpload(return fielRecords)
beforeDelete(return fileRecords)
afterDelete(return fileRecords)

but for now, if you have time will be great to add before delete functionality where the Dev can trigger his own delete function. Thanks for your valuable time.

**Comment by safrazik** [comment]
`beforedelete` event introduced in [Version 1.7.1](https://github.com/safrazik/vue-file-agent/releases/tag/1.7.1). [See Usage](https://safrazik.com/vue-file-agent/docs/#beforedelete). Please note that, if you want to use this event effectively, you should use manual upload instead of auto upload. [See Advanced Usage](https://safrazik.com/vue-file-agent/#advanced-usage)

For other use cases you mentioned, you can already use the [upload events](https://safrazik.com/vue-file-agent/docs/#events) or you can use the [upload methods](https://safrazik.com/vue-file-agent/docs/#methods) that return promise values

**Comment by Gigiart** [comment]
Amazing! thanks Safrazik!
