### ISSUE TITLE
Enable manual uploading

### ISSUE THREAD

**Issue by zl910627** [safrazik/vue-file-agent#64]
![image](https://user-images.githubusercontent.com/53897531/82516928-23de2b00-9b46-11ea-8d3b-cf33b4701625.png)
I am going to upload file to firebase storage using this component.
But due above lines, file delete does not work.
Could you please remove this ?
Thank you.
Zheng

```js
<vue-file-agent
                  v-model="imgPhoto"
                  :meta="false"
                  :multiple="false"
                  :accept="'image/*'"
                  @select="onPhotoChanged"
                  deletable
                  help-text="Photo"
                />
```

**Comment by safrazik** [comment]
Since [Version 1.7.1](https://github.com/safrazik/vue-file-agent/releases/tag/1.7.1) `beforedelete` event was introduced. [See Usage](https://safrazik.com/vue-file-agent/docs/#beforedelete) - to support confirmation, etc. See this issue: #59

When you use manual upload instead of auto upload you are required to listen to the `beforedelete` event. [See Advanced Usage](https://safrazik.com/vue-file-agent/#advanced-usage)

Here is an example implementation for your use case:

```vue
<template>
  <vue-file-agent
    v-model="imgPhoto"
    :meta="false"
    :multiple="false"
    :accept="'image/*'"
    @select="onPhotoChanged"
    deletable
    help-text="Photo"
    @beforedelete="onBeforeDelete($event)"
    @delete="onDelete($event)"
    ref="imgFileAgent"
  />
</template>
<script>
  export default {
    // ...
    metods: {
      // ...
      onBeforeDelete(fileRecord){
         // you can confirm and call the deleteFileRecord method (optional)
         this.$refs.imgFileAgent.deleteFileRecord(fileRecord);
      },
      onDelete(fileRecord){
        // delete from firebase 🔥
      }
      // ...
    }
    // ...
  }
</script>
```
