### ISSUE TITLE
CAN'T DELETE FILES

### ISSUE THREAD

**Issue by vcoromero** [safrazik/vue-file-agent#69]
The event to delete a file isn't working for me
It worked before last version
![InstantGif_2020 06 03-15 23](https://user-images.githubusercontent.com/28553535/83685575-7f7ccf80-a5ae-11ea-8667-d5dd259ca966.gif)

**Comment by safrazik** [comment]
Since [Version 1.7.1](https://github.com/safrazik/vue-file-agent/releases/tag/1.7.1) `beforedelete` event was introduced. [See Usage](https://safrazik.com/vue-file-agent/docs/#beforedelete) - to support confirmation, etc. See this issue: #59

When you use manual upload instead of auto upload you are required to listen to the `beforedelete` event. [See Advanced Usage](https://safrazik.com/vue-file-agent/#advanced-usage)

Here is an example implementation:

```vue
<template>
  <vue-file-agent
    v-model="imgPhoto"
    :meta="false"
    :multiple="false"
    :accept="'image/*'"
    @select="onPhotoChanged"
    deletable
    help-text="Photo"
    @beforedelete="onBeforeDelete($event)"
    @delete="onDelete($event)"
    ref="imgFileAgent"
  />
</template>
<script>
  export default {
    // ...
    metods: {
      // ...
      onBeforeDelete(fileRecord){
         // optionally, you can confirm and call the deleteFileRecord method
         this.$refs.imgFileAgent.deleteFileRecord(fileRecord);
      },
      onDelete(fileRecord){
        // delete from sever
      }
      // ...
    }
    // ...
  }
</script>
```

See also: #64

**Comment by vcoromero** [comment]
Oh I see, thank you so much, I will try it.
