### ISSUE TITLE
Allow changing the multipart parameter

### ISSUE THREAD

**Issue by simpleauthority** [safrazik/vue-file-agent#76]
**Is your feature request related to a problem? Please describe.**
My file server uses a multipart parameter that is not named "file". Now I have to manually edit the file server to use this library.

**Describe the solution you'd like**
Allow us to change the multipart parameter by passing a component prop.

**Describe alternatives you've considered**
Using a different library.

**Additional context**
I don't think there is any.

**Comment by safrazik** [comment]
You can create a custom `FormData` instance with the fourth parameter `createFormData` of `upload`method. [See methods](https://safrazik.com/vue-file-agent/docs/#methods)

Let's assume your server expects parameter `my-file`:

```javascript
// Upload with custom FormData
this.$refs.vueFileAgent.upload(url, headers, fileRecord, function createFormData(fileRecord){
  var formData = new FormData();
  formData.append('custom-id', 123); // any additional POST parameters
  formData.append('my-file', fileRecord.file); // this is important! - the actual file for upload
  return formData;
});
```
See also: https://github.com/safrazik/vue-file-agent/issues/51#issuecomment-611996544
Please note that you have to use manual upload mode instead of auto upload mode. If you want to upload as soon as files are selected/dragged, you can listen to `select` event on the component.

**Comment by simpleauthority** [comment]
Ok, thanks.

**Comment by abelnexus** [comment]
`  formData.append('custom-id', this.id); // any additional POST parameters`

error id is undefined, why ??
