### ISSUE TITLE
Sortable handle lagging issue

### ISSUE THREAD

**Issue by thisisandreww** [safrazik/vue-file-agent#91]
I noticed that once you have uploaded the maximum number of files (set by maxFiles attribute), the sorting handler will not work correctly (lagging / image preview stuck to the mouse) issue. Below the maximum number of files the sorting will work smoothly. Any advise?

**Comment by tommykamkcm** [comment]
@thisisandreww I faced this problem as well and the workaround is to set VueFileAgent readonly to true.
Here is the example
```
<VueFileAgent
...
:maxSize="maxSize"
:readonly="files.length == maxSize"
...
</VueFileAgent>
```

**Comment by safrazik** [comment]
Interesting. I couldn't reproduce the error. @thisisandreww what is the value of `maxFiles` prop when this issue is faced?

**Comment by tommykamkcm** [comment]
I could reproduce the issue at the `Advanced Demo` page, see below:
![image](https://user-images.githubusercontent.com/1722447/93321444-bbc5fa00-f844-11ea-8b6d-8ca6edf2ee6e.png)

Steps to reproduce:
1. Single click (not hold) on either one of the items
2. Move your mouse around

The only way to get rid of the issue is to click any place outside the drag and drop area.

**Comment by thisisandreww** [comment]
> @thisisandreww I faced this problem as well and the workaround is to set VueFileAgent readonly to true.
> Here is the example
> 
> ```
> <VueFileAgent
> ...
> :maxSize="maxSize"
> :readonly="files.length == maxSize"
> ...
> </VueFileAgent>
> ```

Thanks! This seems to be a good workaround for now.
