### ISSUE TITLE
When deleting the uploaded file after uploading to the server, the following error occurs

### ISSUE THREAD

**Issue by hwanideveloper** [safrazik/vue-file-agent#95]
In auto upload mode When deleting the uploaded file after uploading to the server, the following error occurs "org.springframework.web.HttpRequestMethodNotSupportedException: Request method'DELETE' not supported"
But In the state of not in auto upload mod, the delete button works fine.
What is the reason?

**Comment by safrazik** [comment]
Since the error appears to be a server error, the reason may be because you’re not also passing correct `uploadHeaders`. Please debug with the browser’s Network tab to see the difference between the auto and manual requests. See issue #57 for explanation on the importance of `uploadData` in delete request.

 If you are using manual upload in other places, I recommend you to do the same everywhere. You can listen to `select` event for newly added files.

**Comment by hwanideveloper** [comment]
> Since the error appears to be a server error, the reason may be because you’re not also passing correct `uploadHeaders`. Please debug with the browser’s Network tab to see the difference between the auto and manual requests. See issue #57 for explanation on the importance of `uploadData` in delete request.
> 
> If you are using manual upload in other places, I recommend you to do the same everywhere. You can listen to `select` event for newly added files.

Thank you for the answer. When I checked the server side, the error was resolved as both the upload and deletion were saved with the same uploadUrl. It seems to be trying to delete post after uploading in both automatic.

**Comment by safrazik** [comment]
Glad you resolved the error. Closing the issue. Please feel free to reopen if you need more help.
