### ISSUE TITLE
file is removed from fileRecord even though the server return error 500

### ISSUE THREAD

**Issue by fd6130** [safrazik/vue-file-agent#96]
After i uploaded a file and remove it, it will call the DELETE api but when my server return 500 the file from `fileRecords` is removed (the file still remain in my server).

It is very strange to me when the api call return error and it remove the file from the variable. 

```javascript
onDeleteFile: function(fileRecord) {
            var i = this.fileRecordsForUpload.indexOf(fileRecord);
            if (i !== -1) {
                this.fileRecordsForUpload.splice(i, 1);
            } else {
                this.$refs.vueFileAgent
                    .deleteUpload(
                        this.uploadUrl,
                        this.uploadHeaders,
                        fileRecord
                    )
                    .then((responses) => {
                        // handle after success
                    })
                    .catch((responses) => {
                        // handle the error
                    });
            }
```

**Comment by safrazik** [comment]
It appears that in `ajax-request` status code is not respected in [onreadystatechange](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange), instead it relies on [onerror](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onerror) for server errors. (Will be fixed in next version)

https://github.com/safrazik/vue-file-agent/blob/7f7c931b51c8724c852be60a824cac7235c1dad3/src/lib/ajax-request.ts#L61

**Comment by safrazik** [comment]
It looks like, my previous comment is invalid because status validation is already there:

https://github.com/safrazik/vue-file-agent/blob/7f7c931b51c8724c852be60a824cac7235c1dad3/src/lib/ajax-request.ts#L36-L38

When you use manual upload, you have to do it manually too. In auto upload mode, it is handled automatically.

```javascript
onBeforeDelete: function(fileRecord) {
  this.toBeDeletedIndex = this.fileRecords.indexOf(fileRecord.
},
onDeleteFile: function(fileRecord) {
            var i = this.fileRecordsForUpload.indexOf(fileRecord);
            if (i !== -1) {
                this.fileRecordsForUpload.splice(i, 1);
            } else {
                this.$refs.vueFileAgent
                    .deleteUpload(
                        this.uploadUrl,
                        this.uploadHeaders,
                        fileRecord
                    )
                    .then((responses) => {
                        // handle after success
                        this.toBeDeletedIndex = undefined;
                    })
                    .catch((responses) => {
                        // undo removal
                        this.fileRecords.splice(this.toBeDeletedIndex, 0, fileRecord);
                    });
            }
```
